# Maximum number of attempts for code generation to avoid infinite loops. Recommended less then 2500
max-attempts: 1000

modify:
  permission: "redeemx.use.{code}" #You can customize default permission syntax here.

code-minimum-digit: 3             #The minimum digit of code required to generate, default 3 if not specified
code-maximum-digit: 10            #The maximum digit of code required to generate, default 10 if not specified

auto-delete-expired-codes: true   #It will only done when server got restart as it is a heavy operation
auto-delete-redeemed-code-: false
auto-remove-permission-when-redeemed: false


#Set cooldown for using /redeem
cooldown: 3s

renew:
  reset-expired: true
  reset-delay: true
  clear-usage: true
  clear-rewards: false #TODO
  clear-commands: false
  remove-permission-required: false

bot:
  enabled: false
  token: "YOUR_BOT_TOKEN_HERE"

maximum-pool-size: 1  # Adjust the pool size as necessary for your server load

#Don't change it unless you know what you are doing
database-version: 1.0