name: RedeemX
version: 1.3-EAP
main: me.justlime.redeemcodex.RedeemCodeX
api-version: 1.13
softdepend: ["PlaceholderAPI"]

commands:
  rcx:
    usage: "/rcx <subcommand>"
    description: Main command for managing redeemable codes.
    aliases: [redeemx,redeemcodex]
    permission: redeemx.admin.use

  redeem:
    usage: "/redeem <code>"
    description: Redeem a code for rewards.
    permission: redeemx.use
    aliases: [voucher]

permissions:
  redeemx.admin.use.*:
    description: Grants access to all admin commands for RedeemX.
    default: op
    children:
      redeemx.admin.use: true
      redeemx.admin.use.gen: true
      redeemx.admin.use.modify: true
      redeemx.admin.use.delete: true
      redeemx.admin.use.delete_all: true
      redeemx.admin.use.renew: true
      redeemx.admin.use.reload: true
      redeemx.admin.use.info: true
      redeemx.admin.use.preview: true
      redeemx.admin.use.usage: true

  redeemx.admin.use.gen:
    description: Permission to generate redeemable codes.
    default: op

  redeemx.admin.use.modify:
    description: Permission to modify redeemable codes.
    default: op

  redeemx.admin.use.delete:
    description: Permission to delete a specific redeemable code.
    default: op

  redeemx.admin.use.preview:
    description: Permission to preview redeemable codes.
    default: op

  redeemx.admin.use.usage:
    description: Permission to view code usage.
    default: op

  redeemx.admin.use.renew:
    description: Permission to renew codes.
    default: op

  redeemx.admin.use.reload:
    description: Permission to reload the plugin configuration.
    default: op

  redeemx.admin.use.info:
    description: Permission to view plugin information.
    default: op

  redeemx.use:
    description: Permission to redeem codes.
    default: true
